travis:
  secure:
    BINSTAR_TOKEN: IYRSJMehaZFm3LFox/gul+DFj5SU3/9MjzRNjVBOml8OJ9elYfRt3pFICnxXA1z83pOHz/QvBQ8Q5OXjwTA3x87jHTw9zIpF2htwQaV6R3Z7SccH/DlJR1LThiQPclD9xWqJbDAz9CnnpfY47VnCxxHWA2QfaKM8EGj2+CxTiSgM/Gzfmzj6x5AaIxM0BTYYWfGY2wsYcBZGK5Yrei3SO2+L6ufcYuBYFnBfmYq5O3vy7L+fYGVujZvA2SiDsZBZ0hoGpYzyVW9ziLu7kuqMNtPKKG245oGgb9rSOQ637w8wvCe1HXYX7itZsE0IIb3MiyeDWc4Z2zqQ+qZVxYWPkpGV3nBrCqpiUFTvbcLMKKs2qJx5tnEmsn5+JTYgApmlW6+cAWiK1uuFmsGLwk+AckOKv7Y1kNgmtwp94ynp6q+1G7TL07Xt1uyZAVFaOA8GCSBbP8tdWvjfELVSS7imlEo8abu0MaNPdETUUgT5z/Ch3VGVwNdez8xE60qmZU3CKVGUQJcmljU/JJjtIrZHiseLHGurpdd3VVfHMI+QM73+dmrVcJYEsx6MM5x0oOEXDa+UA6qx7HEg5MqdfezbYyIcWGhbS0mPsizKvl/PQWq1PNglqZvqFPagya2QK4P0XThN/veGJDSo31nBXI95ArotH4Kbky7RO7K2RgfGTyc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
